### ISSUE TITLE
make this project linux compliant

### ISSUE THREAD

**Issue by sl1pkn07** [Beatrice-Raws/FFTSpectrum#1]
Hi

seems this project is a windows centric. any plans to make linux compatible?

vapoursynth is multiplatform

greetings

**Comment by soyokaze** [comment]
Hello.

I've added support for GCC with the latest commit. It successfully compiled in Ubuntu 18.04 environment running in WSL.
I'm not able to test it anywhere else at the moment, unfortunately.

**Comment by sl1pkn07** [comment]
Hi. thanks for the work

i think works now

build with this:

~~~
	  gcc -c -fPIC ${CXXFLAGS} ${CPPFLAGS} -I. $(pkg-config --cflags vapoursynth) -o FFTSpectrum.o FFTSpectrum.c
	  gcc -shared $(pkg-config --libs fftw3f) -fPIC ${LDFLAGS} -o lib${_plug}.so FFTSpectrum.o" > Makefile
~~~

without problem

~~~
gcc -c -fPIC -march=native -O2 -pipe -fno-plt -D_FORTIFY_SOURCE=2 -I. -I/usr/include/vapoursynth  -o FFTSpectrum.o FFTSpectrum.c
gcc -shared -lfftw3f  -fPIC -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -o libfftspectrum.so FFTSpectrum.o
~~~

greetings!
